- name: NextCloud Storage Server
  id: nc
  img_src: /assets/img/nextcloud.png
  description_less: NextCloud adalah software open-source yang memungkinkan kamu untuk mencadangkan atau menyimpan data di cloud.
  description_more: >
    <p>Nextcloud ini di buat untuk penyimpanan di salah satu sekolah</p>
  action_buttons: >
    <a href="https://raflimaulanarizki.github.io/2023/07/17/nextcloud.html" target="_blank" class="btn btn-dark mb-1"><i class="fas fa-align-right"></i> &nbsp Blog Post</a>
  tags: [system]


- name: Project Two
  id: p2
  img_src: 
  description_less: Refer to docs to learn how to add your own projects.
  description_more: >
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  action_buttons: >
    <a href="#" target="_blank" class="btn btn-dark mb-1"><i class="fas fa-link"></i> &nbsp View Project</a>
    <a href="#" target="_blank" class="btn btn-dark mb-1"><i class="fas fa-code-branch"></i> &nbsp Repository</a>
    <a href="#" target="_blank" class="btn btn-dark mb-1"><i class="fas fa-align-right"></i> &nbsp Blog Post</a>
  tags: [tag3, docs]
