- name: NextCloud Storage Server
  id: nc
  img_src: /assets/img/nextcloud.png
  description_less: NextCloud adalah software open-source yang memungkinkan kamu untuk mencadangkan atau menyimpan data di cloud.
  description_more: >
   
  action_buttons: >
    <a href="https://raflimaulanarizki.github.io/2023/07/17/nextcloud.html" target="_blank" class="btn btn-dark mb-1"><i class="fas fa-align-right"></i> &nbsp Blog Post</a>
  tags: [system]
